### ISSUE TITLE
ReferenceError: finish is not defined

### ISSUE THREAD

**Issue by DaMaillard** [awslabs/lambda-streams-to-firehose#29] opened 2016-12-08 17:56 UTC
When the lambda authorisation doesn't include 'ListTagsForStream' permission, we can't get the delivery stream name from Kinesis tag. In this case of error, we finish (line 326 in index.js).

At this point, I get the following exception. The problem is reproducible each time, using the 1.4.1 or 1.4.0 

`2016-12-08T17:52:53.127Z	9ada9f25-50a4-4039-9e0e-223cb687004f	ReferenceError: finish is not defined
at Response.<anonymous> (/var/task/index.js:326:3)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:355:18)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:668:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:670:12)`

**Comment by IanMeyers** [comment] 2016-12-08 18:11
Will look into it tomorrow

**Comment by gentax** [comment] 2017-01-27 16:42
any news about this issue? I got it every time and the lambda is not triggered by Kinesis Stream...

**Comment by gentax** [comment] 2017-01-31 14:37
well, @DaMaillard , actually, digging a little bit with some more logs, I got this:
```
message: 'User: arn:aws:sts::732029842021:assumed-role/lambda_basic_execution/LambdaKinesis is not authorized to perform: kinesis:ListTagsForStream on resource: arn:aws:kinesis:eu-west-1:732029842021:stream/test',
code: 'AccessDeniedException'
```

So, simply, add the Kinesis permission to your lambda role and you can forget this issue. 
In my sample above, I added permission to lambda_basic_execution role.

Hope this can help.

**Comment by synhershko** [comment] 2017-02-01 12:49
The issue is that `finish` is defined in method `handler` but was never defined in method `buildDeliveryMap`, that's line 326. A simple test would have caught it.

**Comment by IanMeyers** [comment] 2017-02-01 13:50
This should now be fixed in https://github.com/awslabs/lambda-streams-to-firehose/commit/469b1dc5c239672f10d8927497d0291053f48ed6

**Comment by synhershko** [comment] 2017-02-01 14:00
Not really

```
2017-02-01T13:59:55.258Z	b5452d5a-e886-11e6-860b-673e478fde85	Malformed Kinesis Stream ARN
2017-02-01T13:59:55.380Z	b5452d5a-e886-11e6-860b-673e478fde85	ReferenceError: ERR is not defined
    at Response.<anonymous> (/var/task/index.js:327:45)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:355:18)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
```

**Comment by synhershko** [comment] 2017-02-01 14:12
Btw, the "Malformed Kinesis Stream ARN" error seems to be a bug as well:

In the Lambda Test widget I pick this input test event (generated by the AWS console):

```
{
  "Records": [
    {
      "eventID": "shardId-000000000000:49545115243490985018280067714973144582180062593244200961",
      "eventVersion": "1.0",
      "kinesis": {
        "approximateArrivalTimestamp": 1428537600,
        "partitionKey": "partitionKey-3",
        "data": "SGVsbG8sIHRoaXMgaXMgYSB0ZXN0IDEyMy4=",
        "kinesisSchemaVersion": "1.0",
        "sequenceNumber": "49545115243490985018280067714973144582180062593244200961"
      },
      "invokeIdentityArn": "arn:aws:iam::EXAMPLE",
      "eventName": "aws:kinesis:record",
      "eventSourceARN": "arn:aws:kinesis:EXAMPLE",
      "eventSource": "aws:kinesis",
      "awsRegion": "us-east-1"
    }
  ]
}
```

In the code, you have this:

```javascript
/** function to extract the kinesis stream name from a kinesis stream ARN */
function getStreamName(arn) {
    try {
	var eventSourceARNTokens = arn.split(":");
	return eventSourceARNTokens[5].split("/")[1];
    } catch (e) {
	console.log("Malformed Kinesis Stream ARN");
	return;
    }
}
exports.getStreamName = getStreamName;
```

`eventSourceARNTokens[5]` doesn't exist.

I assume this also affects our realtime stream processing

**Comment by synhershko** [comment] 2017-02-01 14:16
Also, this still happens in other code paths:

```
2017-02-01T14:15:43.699Z	e9980a50-b16b-495f-b982-0b27a82eae8f	ReferenceError: finish is not defined
at Response.<anonymous> (/var/task/index.js:290:3)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:355:18)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:668:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:670:12)
```

**Comment by IanMeyers** [comment] 2017-02-01 14:18
I've now pushed a 1.4.3 without that typo - apologies. As for the ARN issue, the test event isn't a valid ARN. A Valid ARN takes the following form: `arn:aws:kinesis:<region>:<account>:stream/<stream-name>`

**Comment by synhershko** [comment] 2017-02-01 14:20
@IanMeyers please note my other comment on another missing `finish` definition. As for tests, you are literally making it impossible to properly test this Lambda, which should be production grade since it's vendor code and apparently is not.

**Comment by IanMeyers** [comment] 2017-02-01 14:22
This code is an open source contribution from a variety of authors. We always attempt to increase the quality with every commit, and any contributions you might wish to provide in Pull Requests will be gratefully received.

**Comment by IanMeyers** [comment] 2017-02-01 14:26
The final reference to finish function has been removed.

**Comment by IanMeyers** [comment] 2017-02-01 14:31
Having reviewed when/where the changes were made, this issue was introduced through an effort to make the code more modular and include a comprehensive set of tests. These tests are not currently part of the repository, but will be in time.

**Comment by synhershko** [comment] 2017-02-01 20:21
Thanks

**Closed** 2017-04-03 11:14 UTC
