### ISSUE TITLE
Question around boolean `online` variable

### ISSUE THREAD

**Issue by mlazzarini** [awslabs/lambda-streams-to-firehose#52] opened 2017-08-04 15:23 UTC
Hi! First of all thanks for this lambda, it's very useful.

I'm trying to use it to deliver events from a Kinesis stream to Firehose, then S3, without any data transformation. Our architecture is moving towards event sourcing: we have small and frequent events that need to be processed quickly with streams, but we also need to store events to S3 to recover a previous state of the application. So this lambda does exactly what we need.

By the way, I don't understand the meaning of the `online` boolean variable: [here](https://github.com/awslabs/lambda-streams-to-firehose/blob/master/index.js#L136) seems preventing to write all of the events from the stream, but just the first one (within the buffer threshold).

**Comment by dandalf** [comment] 2017-08-08 19:50
I see the same problem with only writing the first event from the stream, and then just skipping the subsequent triggered events.

**Comment by ankon** [comment] 2017-08-24 14:12
Seems this is a duplicate of #53, and supposedly fixed by #54.

**Comment by IanMeyers** [comment] 2017-09-20 15:17
Due to the launch of Kinesis Streams as a source for Kinesis Firehose, if this is the required configuration, then I would direct you to that integration. Otherwise please let me know if this is still an issue.

**Comment by IanMeyers** [comment] 2017-09-20 15:19
I've closed this as the fix to issue 54 should resolve the symptom you are seeing.

**Closed** 2017-09-20 15:19 UTC

**Comment by mlazzarini** [comment] 2017-09-20 15:26
We have configured the stream as a direct source for the delivery stream. Thanks.
